### ISSUE TITLE
How build on Clion Ubuntu 16.04?

### ISSUE THREAD

**Issue by RunningBack33** [ossrs/srs#1273]
`/opt/clion-2018.2.6/bin/cmake/linux/bin/cmake --build /home/runningback33/srs/cmake-build-debug --target srs -- -j 2
[  0%] Building C object CMakeFiles/srs.dir/trunk/research/st/event.c.o
[  1%] Building C object CMakeFiles/srs.dir/trunk/research/st/stk.c.o
/home/runningback33/srs/trunk/research/st/stk.c: In function ‘_st_new_stk_segment’:
/home/runningback33/srs/trunk/research/st/event.c:53:6: error: #error "Only support MD_HAVE_EPOLL"
     #error "Only support MD_HAVE_EPOLL"
      ^
/home/runningback33/srs/trunk/research/st/stk.c:141:6: error: #error "Only Supports Malloc Stack"
     #error "Only Supports Malloc Stack"
      ^
/home/runningback33/srs/trunk/research/st/stk.c:144:20: error: ‘vaddr’ undeclared (first use in this function)
     return (char *)vaddr;
                    ^
/home/runningback33/srs/trunk/research/st/stk.c:144:20: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/srs.dir/build.make:439: ошибка выполнения рецепта для цели «CMakeFiles/srs.dir/trunk/research/st/stk.c.o»
make[3]: *** [CMakeFiles/srs.dir/trunk/research/st/stk.c.o] Ошибка 1
make[3]: *** Ожидание завершения заданий…
CMakeFiles/srs.dir/build.make:374: ошибка выполнения рецепта для цели «CMakeFiles/srs.dir/trunk/research/st/event.c.o»
make[3]: *** [CMakeFiles/srs.dir/trunk/research/st/event.c.o] Ошибка 1
CMakeFiles/Makefile2:72: ошибка выполнения рецепта для цели «CMakeFiles/srs.dir/all»
make[2]: *** [CMakeFiles/srs.dir/all] Ошибка 2
CMakeFiles/Makefile2:84: ошибка выполнения рецепта для цели «CMakeFiles/srs.dir/rule»
make[1]: *** [CMakeFiles/srs.dir/rule] Ошибка 2
Makefile:118: ошибка выполнения рецепта для цели «srs»
make: *** [srs] Ошибка 2`

How I can fixed this?
