### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Baa14453** [ossrs/srs#1159]
Hello,
I am trying to compile on Ubuntu 18.04 by running `./configure --full && make`
I get the following error, which seems similar to [1065](https://github.com/ossrs/srs/issues/1065).
```

src/core/ngx_murmurhash.c: In function ‘ngx_murmur_hash2’:
src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[2] << 16;
         ~~^~~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:38:5: note: here
     case 2:
     ^~~~
src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[1] << 8;
         ~~^~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:40:5: note: here
     case 1:
     ^~~~
cc1: all warnings being treated as errors
objs/Makefile:429: recipe for target 'objs/src/core/ngx_murmurhash.o' failed
make[1]: *** [objs/src/core/ngx_murmurhash.o] Error 1
make[1]: Leaving directory '/home/baa/srs/srs/trunk/objs/nginx-1.5.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
build nginx-1.5.7 failed, ret=2

```

**Comment by wnpllrzodiac** [comment]
High version gcc semantic  check is more strict？

**Comment by winlinvip** [comment]
What's your SRS version? SRS2?

**Comment by Baa14453** [comment]
I don't have the directory anymore, but I think it was SRS2, yes

**Comment by wwng2333** [comment]
Plz try use build with ubuntu 16.04.

**Comment by winlinvip** [comment]
OK, I'll have a look.

**Comment by winlinvip** [comment]
Dup #1065

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/a554dd85e110ca4ce9ec35423c9886edaff90371 in 2.0.263

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/a554dd85e110ca4ce9ec35423c9886edaff90371 in 2.0.263
