### ISSUE TITLE
configure failed when compile on Ubuntu 18.04 LTS 

### ISSUE THREAD

**Issue by dmoons** [ossrs/srs#1154]
Ubuntu is most recently release  Ubuntu 18.04 LTS
Linux version 4.15.0-22-generic (buildd@lgw01-amd64-013) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018

dmoons@ubuntu:~/srs/trunk$ sudo ./configure
[sudo] password for dmoons:
regenerate config: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --without-nginx --with-ssl --without-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --without-stream-caster --with-http-api --with-librtmp --without-research --with-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
check gcc/g++/gdb/make
depends tools are ok
Ubuntu detected, install tools if needed
Ubuntu install tools success
SED is sed_utility
st-1.9t is ok.
build http-parser-2.1
patching file Makefile
cc -I. -DHTTP_PARSER_STRICT=1  -Wall -Wextra -Werror -O0 -g  -c http_parser.c
http_parser.c: In function ‘http_parser_parse_url’:
http_parser.c:2093:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;
         ~~~~~~~~~^~~
http_parser.c:2096:7: note: here
       case s_req_server:
       ^~~~
cc1: all warnings being treated as errors
Makefile:40: recipe for target 'http_parser.o' failed
make: *** [http_parser.o] Error 1
build http-parser-2.1 failed, ret=2

**Comment by dmoons** [comment]
same as #1065

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/a554dd85e110ca4ce9ec35423c9886edaff90371 in 2.0.263
